### ISSUE TITLE
How to reproduce the architecture of this article

### ISSUE THREAD

**Issue by JackyLin7414** [zhouhuan-hust/DiCNet#1]
Hi @zhouhuan-hust ,

I am very interested in this paper.
Can you tell me how to reproduce it?

Thank you. I appreciate it

Jacky

**Comment by zhouhuan-hust** [comment]
Hello Jacky, thank you for your attention. I'll sort out my code and upload it shortly.

**Comment by JackyLin7414** [comment]
Thank you very much. I appreciate it.
